---
- name: Set up Homelab Server Environment
  hosts: homelabs
  vars_files:
    - vars/default.yml
    - [ "vars/secrets.yml", "vars/secrets.yml.example" ]

  roles:
    - role: system
    - role: git
    - role: zsh
    - role: neovim
